content_access_roles_gids:
  anonymous: 1
  authenticated: 2
  administrator: 3
  sailor_registry_members: 4
_core:
  default_config_hash: 7LkiviGITIpniIOOIzpuxR7r4XzqqYN_cwu0fb0kx1M
langcode: lv
content_access_node_type:
  page: 'a:1:{s:8:"per_node";i:1;}'
