api_url: api.drupal.org
page_alter: false
raw_names: false
error_handlers:
  1: 1
rebuild_theme: false
debug_mail_file_format: '%to-%subject-%datetime.mail.txt'
debug_mail_directory: 'temporary://devel-mails'
_core:
  default_config_hash: a9KObOzARMPO0Jb5FNTpYcjGv6z-Zr0QU27y9PRGAE4
langcode: lv
