general_settings:
  radio_behavior: simple
  context_lines_leading: 1
  context_lines_trailing: 1
  revision_pager_limit: 50
  layout_plugins:
    split_fields:
      enabled: true
    unified_fields:
      enabled: true
    visual_inline:
      enabled: true
_core:
  default_config_hash: 2GE7UJUi0iGBPVb9DkGqN4bHjIsphvlb2DM8a-uej4s
langcode: lv
content_type_settings:
  page:
    view_mode: ''
  article:
    view_mode: ''
  legislation:
    view_mode: ''
  forms:
    view_mode: ''
  background_images:
    view_mode: ''
  contact:
    view_mode: ''
  tenders:
    view_mode: ''
