custom:
  -
    path: /
entity_types:
  node:
    page:
      index: 0
      priority: 0.5
    article:
      index: 1
      priority: 0.5
    contact:
      index: 1
      priority: 0.1
  menu_link_content:
    main:
      index: 1
      priority: !!float 0
    about:
      index: 1
      priority: 0.5
settings:
  max_links: 2000
  cron_generate: true
  remove_duplicates: true
  batch_process_limit: 1500
_core:
  default_config_hash: 3tLXpniLSox7SYSaEU68-Eevb2aDnEYtJ9uufBwmKZw
langcode: lv
