label: 'EForm Submissions'
description: '@todo submission description'
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: '‹ previous'
            next: 'next ›'
            first: '« first'
            last: 'last »'
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      fields:
        eform_submission_bulk_form:
          label: 'Bulk update'
          action_title: 'With selection'
        uid:
          label: Submitter
          separator: ', '
        created:
          label: Submitted
        view_eform_submission:
          label: View
          text: view
        operations:
          label: Operations
      arguments:
        type:
          exception:
            title: All
          title: 'Submissions for %1'
      title: 'Report 2'
  embed_1:
    display_title: Embed
    display_options:
      title: 'Report 1'
  embed_2:
    display_title: Embed
